name: Upstream

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Automatic upstream
    runs-on: ubuntu-20.04
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install git
    - name: Upstream branches
      run: |
        git config --global user.name "${KIAM_USER}"
        git config --global user.email "${KIAM_EMAIL}"
        git clone https://"${KIAM_USER}":"${KIAM_TOKEN}"@github.com/"${KIAM_USER}"/releases.git
        cd releases
        function upstream() { for var in sakura-vayu; do git checkout $var; git rebase master; git push -f; done; git checkout master; }
        upstream
      env:
        KIAM_EMAIL: ${{ secrets.KIAM_EMAIL }}
        KIAM_TOKEN: ${{ secrets.KIAM_KEY }}
        KIAM_USER: ${{ secrets.KIAM_USER }}
